extend type Query {
  """
  ✨ Look up a single `LearningModule` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  learningModule(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LearningModule_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LearningModule_FirstRow
  ): LearningModule @fdc_generated(from: "LearningModule", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Note` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  note(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Note_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Note_FirstRow
  ): Note @fdc_generated(from: "Note", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Project` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  project(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow
  ): Project @fdc_generated(from: "Project", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Task` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  task(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Task_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Task_FirstRow
  ): Task @fdc_generated(from: "Task", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserLearningProgress` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userLearningProgress(
    """
    The key used to identify the object.
    """
    key: UserLearningProgress_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserLearningProgress_FirstRow
  ): UserLearningProgress @fdc_generated(from: "UserLearningProgress", purpose: QUERY_SINGLE)
  """
  ✨ List `LearningModule` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  learningModules(
    """
    Filter condition to narrow down the query results.
    """
    where: LearningModule_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LearningModule_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LearningModule_Having
  ): [LearningModule!]! @fdc_generated(from: "LearningModule", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Note` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  notes(
    """
    Filter condition to narrow down the query results.
    """
    where: Note_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Note_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Note_Having
  ): [Note!]! @fdc_generated(from: "Note", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Project` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  projects(
    """
    Filter condition to narrow down the query results.
    """
    where: Project_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Project_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Project_Having
  ): [Project!]! @fdc_generated(from: "Project", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Task` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tasks(
    """
    Filter condition to narrow down the query results.
    """
    where: Task_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Task_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Task_Having
  ): [Task!]! @fdc_generated(from: "Task", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserLearningProgress` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userLearningProgresses(
    """
    Filter condition to narrow down the query results.
    """
    where: UserLearningProgress_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserLearningProgress_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserLearningProgress_Having
  ): [UserLearningProgress!]! @fdc_generated(from: "UserLearningProgress", purpose: QUERY_MULTIPLE)
}
